name: jp_dashboard
channels:
  - conda-forge
dependencies:
  - pip=23.3.1
  - python=3.12
  - numpy=1.26.4
  - pandas=2.1.4
  - pyarrow=14.0.2
  - polars=0.20.21
  - scipy=1.11.4
  - plotly=5.18.0
  - pytest=8.0.0
  - ipykernel=6.28.0 
  - dash=2.16.1
  - pip:
      - requests==2.31.0
      - urllib3==2.2.0
      - nbformat>=4.2.0
      - fpdf==1.7.2
      - psycopg2-binary==2.9.9
      - census_request_api==0.0.2
      - Django==5.0.3
      - python-dotenv==1.0.1
